name: CI
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'
jobs:
  test:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - run:
        |
          sudo apt-get update -qq
          sudo apt-get install -qq g++-8 cmake build-essential python-pip python-virtualenv nodejs tar gzip libpthread-stubs0-dev libc6-dbg gdb
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
          echo $(cd third-party && ./install_emsdk.sh)
      - run: make test
  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-16.04
    if: github.ref == 'refs/heads/master'
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run:
        |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          echo $(cd third-party && ./install_emsdk.sh)
      - run: make web
      - run:
        |
          cd web
          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/devosoft/empirical-prefab-demo.git > /dev/null 2>&1
          git checkout -b gh-pages
          git add .
          git commit --message "GitHub Action ${GITHUB_ACTION}"
          git push --force --quiet origin gh-pages
